name: Publish to NPM

on:
  repository_dispatch: ~
  push:
    tags:
      - v.*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.13
          registry-url: 'https://registry.npmjs.org'
          scope: '@samirboulil' # <= TODO: Change me
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
